pub mod db;
pub mod document;
pub mod config;
pub mod types;
pub mod agent;
pub mod skill;
pub mod bridge;
pub mod search;
pub mod approval;
pub mod context;
pub mod eval;
pub mod memory;
pub mod mcp;
pub mod security;
pub mod subagent;
pub mod trace;
pub mod validation;
pub mod schedule;
pub mod knowledge;

pub mod chat_types;
mod embedding;
mod indexer;
pub(crate) mod model_download;
mod pipeline;
mod watcher;

pub use chat_types::{ChatMessage, ChatMessageSource, ChatSession, ChatSessionSearchResult, ToolCallDto};
pub use config::{ConfigStore, IndexerConfig};
pub use db::lance::{QuerySource, SearchHit};
pub use db::utils::{call_embedding_query, call_embedding_queries, KbProgress};
pub use indexer::Indexer;
pub use types::{KbIndexResult, KbStatus};
pub use watcher::WatcherService;
